from firecrawl import FirecrawlApp, ScrapeOptions

app = FirecrawlApp(api_key="your api key")

# Crawl a website:
crawl_result = app.crawl_url(
  'website url', 
  limit=10, # crawl upto max 10 subpages 
  scrape_options=ScrapeOptions(formats=['markdown', 'html']),
)


# dumping into a file, before that we need convert some of the stuff to handle the results generated by scrappong.

import json
from datetime import datetime

def default_encoder(obj):
    if isinstance(obj, datetime):
        return obj.isoformat()  # Converts datetime to string
    raise TypeError(f"Object of type {obj.__class__.__name__} is not JSON serializable")

with open('results.txt', 'w') as f:
    f.write(json.dumps(crawl_result.model_dump(), indent=2, default=default_encoder))


